/* create table to hold all starting recipes */
CREATE TABLE base_recipes (
    recipe_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    base_name TEXT NOT NULL,
    ingredients TEXT NOT NULL,
    steps TEXT NOT NULL
);
