CREATE OR REPLACE FUNCTION trigger_set_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.date_modified = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql; 

CREATE TABLE fused_recipes (
    fused_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    fused_name TEXT NOT NULL,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL,
    date_modified TIMESTAMPTZ NOT NULL,
    fuse_ingredients TEXT NOT NULL,
    fuse_steps TEXT NOT NULL
);

CREATE TRIGGER set_timestamp
BEFORE UPDATE ON fused_recipes
FOR EACH ROW
EXECUTE PROCEDURE trigger_set_timestamp();